name: Gemini Dev Agent

on:
  issues:
    types: [opened]

    push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      issue_number:
        description: 'The Issue # to work on'
        required: true
        type: string

permissions:
  issues: write
  contents: write

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install google-generativeai PyGithub

      - name: Run agent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

        run: python agent/agent.py
